# Generated by Django 5.0.6 on 2024-05-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_note_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ('priority', '-publish')},
        ),
        migrations.AddField(
            model_name='note',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
